theme: jekyll-theme-minimal
title: Placebo Imaging Consortium
description: Ulrike Binel, Tor Wager, Matthias Zunhammer, Tamas Spisak
logo: fig/logo.png
google_analytics: UA-120757757-4
plugins:
  - jemoji
